
print("Olá!")
print("Somos a empresa Chevrolet e necessitamos de suas informações para o cadastro:")
name= input("Digite seu nome:")
Idade= input("Digite sua idade:")
Genero= input("Digite seu sexo:")
Telefone= input("Digite seu telefone:")
Email= input("Digite seu E-mail:")
Cidade= input("Digite sua cidade:")
saudacao= ("Caro")
if Genero == "Feminino": saudacao= ("Cara")
if Idade >= 120 :print("Por favor, digite sua verdadeira idade!!"), exit, 
print(saudacao, name ," Seu cadastro foi realizado com sucesso!")
print("Fique atento as novas atualizações deste serviço")
print("Obrigado pela atenção!")
